In [1]:
pip install transformers

In [2]:
from transformers import pipeline


In [3]:
import transformers
print(transformers.__version__)

4.51.1


In [4]:
#import libraries
# python packages  for audio video analysis
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np



In [5]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [7]:
#audio,samppling_rate = librosa.load('/content/आईवर सादर केलेली कविता _ संकर्षण कऱ्हाडे _ Mother Poem _2 9M views · 47K reactions.m4a',sr= 16000)
audio,sampling_rate = librosa.load('/content/“Education is the... __ Nelson Mandela quotes.m4a',sr=16000)

<ipython-input-7-c68fa20c009a>:2: UserWarning: PySoundFile failed. Trying audioread instead.
  audio,sampling_rate = librosa.load('/content/“Education is the... __ Nelson Mandela quotes.m4a',sr=16000)
/usr/local/lib/python3.11/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


In [10]:
audio,sampling_rate

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 16000)

In [11]:
#display.Audio('/content/आईवर सादर केलेली कविता _ संकर्षण कऱ्हाडे _ Mother Poem _2 9M views · 47K reactions.m4a',autoplay=True)  long video about 3 minutes
display.Audio('/content/“Education is the... __ Nelson Mandela quotes.m4a',autoplay=True)

In [12]:
input_values = tokenizer(audio,return_tensors='pt').input_values
input_values

tensor([[0.0023, 0.0023, 0.0023,  ..., 0.0023, 0.0023, 0.0023]])

In [13]:
logits = model(input_values).logits
logits

tensor([[[ 14.2641, -28.5482, -28.2249,  ...,  -7.0742,  -7.6322,  -7.4051],
         [ 14.2819, -28.6158, -28.2910,  ...,  -7.0840,  -7.6519,  -7.4080],
         [ 14.3042, -28.6339, -28.3073,  ...,  -7.0899,  -7.6503,  -7.4164],
         ...,
         [ 14.3306, -28.6570, -28.3479,  ...,  -6.8945,  -7.4992,  -7.1720],
         [ 14.3963, -28.7123, -28.3890,  ...,  -7.0159,  -7.7351,  -7.2232],
         [ 14.5190, -28.8571, -28.5239,  ...,  -7.2829,  -8.0414,  -7.4202]]],
       grad_fn=<ViewBackward0>)

In [14]:
predicted_ids = torch.argmax(logits,dim=-1)


In [15]:
transcription= tokenizer.decode(predicted_ids[0])

In [16]:
transcription

'EDUCATION IS THE MOST POWERFUL WEAPON WHICH YOU CAN USE TO CHANGE THE WORLD'